
image: fedora:latest

before_script:
  - python3 -V
  - rpm -q fedora-release-common
  - dnf install -y which python-pip gcc python3-devel dialog git
  - pip install setuptools cython numpy pandas flake8 pre-commit

lint:
  script:
    - pre-commit clean
    - pre-commit run --all-files
  after_script:
    - git diff

run:
  script:
    - python3 setup.py sdist
  artifacts:
    paths:
      - dist/*.tar.gz

pages:
  stage: deploy
  script:
  - python3 setup.py install
  - pip3 install -U sphinx
  - sphinx-build -b html source public
  artifacts:
    paths:
    - public
  only:
    - master
