
image: fedora:latest

before_script:
  - python3 -V
  - rpm -q fedora-release-common
  - dnf install -y which python-pip gcc python3-devel dialog git
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry config pypi-token.pypi ${PYPI_TOKEN}
  - poetry install -vv

lint:
  script:
    - poetry run pre-commit clean
    - poetry run pre-commit run --all-files
  after_script:
    - git diff

run:
  script:
    - poetry build -f sdist
  artifacts:
    paths:
      - dist/*.tar.gz

publish:
  before_script:
    - poetry build -f sdist
  script:
    - poetry publish
  only:
    - tags

pages:
  stage: deploy
  script:
    - poetry run sphinx-build -b html source public
  artifacts:
    paths:
    - public
  only:
    - master
