image: fedora:latest

stages:
  - lint
  - build
  - deploy

before_script:
  - python3 -V
  - rpm -q fedora-release-common
  - dnf install -y which python-pip gcc python3-devel dialog git
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry install -vv

lint-check:
  stage: lint
  script:
    - poetry run pre-commit clean
    - poetry run pre-commit run --all-files
  after_script:
    - git diff

build-sdist:
  stage: build
  script:
    - poetry build -f sdist
  artifacts:
    paths:
      - dist/*.tar.gz

publish:
  stage: deploy
  script:
    - poetry config pypi-token.pypi ${PYPI_TOKEN}
    - poetry build -f sdist
    - poetry publish
  only:
    - tags

pages:
  stage: deploy
  script:
    - poetry run sphinx-build -b html source public
  artifacts:
    paths:
      - public
  only:
    - master
